# [x] EQSTA not getting included w CONTROL command
# [x] LOCGRID and VGGRID don't have same default value for top of grid
# [x] Taka example should use --sta-fmt STA not NET_STA
# [x] LOCGRID needs to be centered by default
# TODO Is utils/quakeml.convert_quakeml_to_nonlinloc_obs necessary; why are there basically duplicate methods?
# [x] Create configuration from lat,lon,radius,datasource
# [x] $ nllpy gtsrce https://service.iris.washington.edu --lat 46.51 --lon 8.48 --rad_km 50.0 --sta-fmt NET_STA > gtsrce.in
# TODO $ nllpy control --template volcano --lat 46.51 --lon 8.48 --elev 3248 --rad_km 50.0 --gridkm 100,100,1.0 --depthkm 50,1.0 --inventory https://service.iris.edu --output volcano.in
#   - get all statiosn from FDSN url within 50.0 km of lat,lon, defines VGGRID and LOCCGRID accordingly, and outputs control file
# [x]    also needs --sig 'VDAP' --com 'Auto-generated by nllpy' --model 'vdap_stratovolcano' --prefix spurr --trans SDC (including all that stuff should eliminate need for --template volcano
# [x] Add command line tool for EQSTA
# [x] Create an bash script example from scratch
# - define volcano lat,lon,elevation,radius
# - get inventory
# - get events
# - define region based on lat,lon,delta,inventory,velocity_model
# - run NonLinLoc
# - plot original locations with new NLL locations in GMT
# TODO Pair down control file to simplest possible parts
# TODO Create locgrid from distx,disty,delta (vggrid, locgrid, grid(both))
# [x] Add functionality to overwrite existing control file
# [x] $ nllpy control --template volcano --output volcano.in
# [x] $ nllpy control --template volcano.in --lat 46.51 --lon 8.48 --elev 3248 --output volcano.in
# [x] $ nllpy control --template volcano.in --sig 'Cascades Volcano Observatory' --com 'Mount St Helens' --prefix 'msh' --output volcano.in
# [x] Create examples in README.
# [x] When getting events from USGS FDSN, assign phase hint based on channel
# TODO Add NLLROOT
# TODO Command to create directory structure, make directories if necessary
# [x] Command to convert FDSN station format to NLL
# TODO config.snap_grid_to_elevation(3424, vggrid=True, locgrid=True)  # Snap to -4 (based on d_grid_z)
# TODO config.set_resolution(1.0, vgrid=True, locgrid=True)  # Set grid resolution in all dimensions to 1.0
# TODO config.set_velocity_model("/path/to/model.txt", format="SIMPLE")
# TODO config.set_stations("/path/to/inventory.txt", format="FDSN")
# TODO Add NLLPATH
# TODO Add commands to run Vel2Grid, Grid2Time, NLLoc
# config.run_nll(vel2grid=False, grid2time=False, nlloc=True)
# TODO Add commands to read/plot results

# TODO Move nllpy/utils/quakeml.py to vdapseisutils/utils/obspy/catalog.py


# TODO DETECTION->ASSOCIATION->LOCATION (EQTRANSFOMER->PYOCTO-NONLINLOC)
# input: vlat, vlon, velev, t1, t2, datasource, inventory, velocity_model
#